var submissionID = "";

function displayLink(id) {
    if (id == null || id[0] == null) {
        document.querySelector(".input-group").style.display = "none";
        document.querySelector(".container").innerHTML += `
    <div class="alert alert-warning" role="alert" style="background-color: #e6f7ff;">
  Sorry, There is no link available current browser tab.
  Please make sure you are in the <strong>"My submission"</strong> tab  
</div>
    `;
    } else {
        submissionID = id[0].substring(0, id[0].indexOf("~"));
        chrome.tabs.query(
            { active: true, currentWindow: true },
            function (tab) {
                let fromIndex = 0;
                let countSlash = 0;
                while (tab[0].url.indexOf("/", fromIndex) != -1) {
                    fromIndex = tab[0].url.indexOf("/", fromIndex + 1);
                    countSlash++;
                    if (countSlash >= 8) break;
                }
                document.querySelector("#shareLink").value =
                    tab[0].url.substring(0, fromIndex) +
                    "/review/" +
                    submissionID;
            }
        );
    }
}

chrome.tabs.query({ active: true }, function (tabs) {
    var tab = tabs[0];
    tab_title = tab.title;
    chrome.tabs.executeScript(
        tab.id,
        {
            code: 'document.getElementsByClassName("cds-input-input")[0].id',
        },
        displayLink
    );
});

window.onload = function () {
    "use strict";

    function copyToClipboard(elem) {
        var target = elem;

        var currentFocus = document.activeElement;

        target.focus();
        target.setSelectionRange(0, target.value.length);

        var succeed;

        try {
            succeed = document.execCommand("copy");
        } catch (e) {
            console.warn(e);

            succeed = false;
        }

        if (currentFocus && typeof currentFocus.focus === "function") {
            currentFocus.focus();
        }

        if (succeed) {
            document.getElementsByClassName("copied")[0].style.display =
                "inline";
        }

        return succeed;
    }
    document
        .getElementById("copyButton")
        .addEventListener("click", function () {
            copyToClipboard(document.getElementById("shareLink"));
        });
    document.getElementById("shareLink").addEventListener("click", function () {
        copyToClipboard(document.getElementById("shareLink"));
    });
};

window.onload = function () {
    // Mảng chứa các từ hoặc cụm từ cơ bản
    const words = [
        "ability",
        "account",
        "action",
        "activity",
        "administration",
        "adult",
        "agency",
        "agent",
        "age",
        "agreement",
        "ahead",
        "air",
        "all",
        "amount",
        "analysis",
        "animal",
        "answer",
        "anyone",
        "anything",
        "area",
        "arm",
        "art",
        "article",
        "artist",
        "author",
        "authority",
        "attorney",
        "audience",
        "bag",
        "bank",
        "bar",
        "base",
        "bed",
        "behavior",
        "benefit",
        "best",
        "better",
        "between",
        "bill",
        "billion",
        "bit",
        "black",
        "blood",
        "blue",
        "board",
        "body",
        "book",
        "brother",
        "budget",
        "building",
        "business",
        "camera",
        "campaign",
        "cancer",
        "candidate",
        "capital",
        "car",
        "card",
        "career",
        "case",
        "cause",
        "center",
        "challenge",
        "chance",
        "charge",
        "child",
        "choice",
        "church",
        "citizen",
        "city",
        "civil",
        "claim",
        "class",
        "collection",
        "college",
        "color",
        "commercial",
        "community",
        "company",
        "computer",
        "concern",
        "conference",
        "consumer",
        "country",
        "couple",
        "course",
        "court",
        "cover",
        "crime",
        "culture",
        "cup",
        "data",
        "daughter",
        "day",
        "deal",
        "death",
        "debate",
        "decade",
        "decision",
        "degree",
        "Democrat",
        "design",
        "detail",
        "development",
        "difference",
        "dinner",
        "direction",
        "director",
        "disease",
        "discussion",
        "doctor",
        "dog",
        "door",
        "dream",
        "drug",
        "each",
        "east",
        "education",
        "effect",
        "effort",
        "eight",
        "election",
        "employee",
        "end",
        "energy",
        "evening",
        "event",
        "evidence",
        "example",
        "executive",
        "experience",
        "expert",
        "face",
        "fact",
        "factor",
        "family",
        "field",
        "fight",
        "figure",
        "finger",
        "fire",
        "firm",
        "fish",
        "floor",
        "food",
        "foot",
        "force",
        "foreign",
        "friend",
        "game",
        "garden",
        "gas",
        "generation",
        "girl",
        "glass",
        "goal",
        "government",
        "ground",
        "group",
        "gun",
        "guy",
        "hair",
        "hand",
        "health",
        "history",
        "home",
        "hope",
        "hospital",
        "hour",
        "house",
        "human",
        "husband",
        "idea",
        "image",
        "impact",
        "industry",
        "information",
        "interest",
        "investment",
        "issue",
        "item",
        "job",
        "kid",
        "kitchen",
        "knowledge",
        "land",
        "language",
        "law",
        "lawyer",
        "leader",
        "life",
        "light",
        "line",
        "list",
        "little",
        "local",
        "loss",
        "love",
        "machine",
        "magazine",
        "manager",
        "market",
        "marriage",
        "material",
        "matter",
        "media",
        "medical",
        "meeting",
    ];

    const words2 = [
        "innovation",
        "focus",
        "passion",
        "vision",
        "learning",
        "growth",
        "resilience",
        "patience",
        "motivation",
        "discipline",
        "clarity",
        "strategy",
        "ambition",
        "achievement",
        "potential",
        "energy",
        "confidence",
        "teamwork",
        "leadership",
        "inspiration",
        "effort",
        "integrity",
        "openness",
        "adaptability",
        "communication",
        "knowledge",
        "understanding",
        "expertise",
        "collaboration",
        "positivity",
        "dedication",
        "precision",
        "transformation",
        "commitment",
        "partnership",
        "consistency",
        "trust",
        "empathy",
        "insight",
        "respect",
        "creativity",
        "support",
        "balance",
        "empathy",
        "stamina",
        "success",
        "development",
        "perspective",
        "effectiveness",
        "awareness",
        "persistence",
        "reflection",
        "direction",
        "impact",
        "competence",
        "calmness",
        "determination",
        "visionary",
        "ambitious",
        "collaborative",
        "realization",
        "creativity",
        "challenges",
        "realization",
        "realization",
        "productivity",
        "accountability",
        "persistence",
        "advancement",
        "wisdom",
        "potential",
        "realism",
        "ambitious",
        "values",
        "satisfaction",
        "opportunity",
        "insightful",
        "breakthrough",
        "engagement",
        "competence",
        "learning",
        "stability",
        "preparation",
        "dedication",
        "willpower",
        "optimism",
        "guidance",
        "initiative",
        "mastery",
        "excellence",
        "success",
        "inclusion",
        "progression",
        "passionate",
        "direction",
        "clarity",
        "knowledge",
        "feedback",
        "wisdom",
        "perseverance",
        "preparation",
        "openness",
        "focus",
        "endurance",
        "growth",
        "responsibility",
        "clarity",
        "stamina",
        "proactiveness",
        "compassion",
        "creative",
        "problem-solving",
        "understanding",
        "success",
        "empathy",
        "efficiency",
        "objectives",
        "achievement",
        "tenacity",
        "challenges",
        "proactive",
        "strategy",
        "dreams",
        "patience",
        "commitment",
        "perfection",
        "integrity",
        "opportunity",
        "experience",
        "transparency",
        "leadership",
        "objectives",
        "engagement",
        "strategy",
        "alignment",
        "cooperation",
        "patience",
        "decisiveness",
        "results",
        "execution",
        "visionary",
        "problems",
        "leadership",
        "insight",
        "communication",
        "ambition",
        "learning",
        "achievement",
        "solutions",
        "inspiration",
        "potential",
        "success",
        "commitment",
        "vision",
        "teamwork",
        "growth",
        "creativity",
        "perseverance",
        "patience",
        "determination",
        "responsibility",
        "tenacity",
        "consistency",
        "progression",
        "insight",
        "strategy",
        "clarity",
        "visionary",
        "perspective",
        "ambition",
        "strategy",
        "efficiency",
        "visionary",
        "calmness",
        "confidence",
        "solutions",
        "endurance",
        "consistency",
        "strength",
        "leadership",
        "collaboration",
        "visionary",
        "resilience",
        "leadership",
        "persistence",
        "mastery",
        "progression",
        "tenacity",
        "progress",
        "responsibility",
        "problem-solving",
        "optimism",
        "inclusiveness",
        "teamwork",
        "objectives",
        "visionary",
        "decisiveness",
        "accountability",
        "clarity",
        "knowledge",
        "development",
        "expertise",
        "communication",
        "visionary",
        "perseverance",
        "proactive",
        "perfection",
        "learning",
        "strategy",
        "creativity",
        "collaboration",
        "leadership",
        "potential",
        "insight",
        "solutions",
        "responsibility",
        "empathy",
        "solutions",
        "responsibility",
        "clarity",
        "understanding",
        "innovation",
        "dedication",
        "stamina",
        "leadership",
        "engagement",
        "clarity",
        "ambition",
        "knowledge",
        "excellence",
        "visionary",
        "progression",
        "solutions",
        "potential",
        "confidence",
        "results",
        "confidence",
        "insight",
        "innovation",
        "efficiency",
        "clarity",
        "leadership",
        "endurance",
        "visionary",
        "clarity",
        "creativity",
        "competence",
        "innovation",
        "ambition",
        "patience",
        "visionary",
        "communication",
        "strategy",
        "motivation",
        "competence",
        "vision",
        "clarity",
        "potential",
        "confidence",
        "stamina",
        "solutions",
        "motivation",
        "success",
        "creativity",
        "determination",
        "innovation",
        "excellence",
        "perfection",
        "achievement",
        "leadership",
        "success",
        "engagement",
        "resilience",
        "creativity",
        "clarity",
        "strength",
        "success",
        "accountability",
        "clarity",
        "empathy",
        "confidence",
        "solutions",
        "confidence",
        "ambition",
        "potential",
        "clarity",
        "determination",
        "success",
        "excellence",
        "solutions",
        "vision",
        "clarity",
        "potential",
        "ambition",
        "stamina",
        "creativity",
        "patience",
        "stamina",
        "clarity",
        "potential",
        "excellence",
        "confidence",
        "stamina",
        "success",
        "responsibility",
        "ambition",
        "stamina",
        "clarity",
        "progression",
        "confidence",
        "vision",
        "clarity",
        "potential",
        "solutions",
        "clarity",
        "progress",
        "results",
        "patience",
        "confidence",
        "vision",
        "engagement",
        "success",
        "vision",
        "clarity",
        "potential",
        "clarity",
        "progression",
    ];
    const verbs = [
        "able",
        "accept",
        "act",
        "add",
        "address",
        "admit",
        "affect",
        "agree",
        "allow",
        "appear",
        "apply",
        "argue",
        "arrive",
        "ask",
        "assume",
        "attack",
        "avoid",
        "beat",
        "become",
        "believe",
        "bring",
        "build",
        "call",
        "carry",
        "catch",
        "change",
        "check",
        "choose",
        "come",
        "compare",
        "concern",
        "consider",
        "continue",
        "control",
        "create",
        "decide",
        "decrease",
        "describe",
        "develop",
        "die",
        "discuss",
        "discover",
        "drive",
        "eat",
        "enjoy",
        "enter",
        "establish",
        "expect",
        "experience",
        "explain",
        "feel",
        "find",
        "finish",
        "follow",
        "get",
        "give",
        "go",
        "grow",
        "happen",
        "have",
        "hear",
        "help",
        "hold",
        "hope",
        "improve",
        "include",
        "indicate",
        "involve",
        "keep",
        "know",
        "lead",
        "learn",
        "leave",
        "let",
        "like",
        "live",
        "look",
        "lose",
        "love",
        "make",
        "manage",
        "mean",
        "meet",
        "move",
        "need",
        "offer",
        "open",
        "pass",
        "pay",
        "plan",
        "play",
        "provide",
        "reach",
        "read",
        "realize",
        "receive",
        "recognize",
        "reduce",
        "remember",
        "represent",
        "require",
        "return",
        "run",
        "say",
        "see",
        "sell",
        "send",
        "set",
        "show",
        "speak",
        "spend",
        "start",
        "stop",
        "take",
        "talk",
        "tell",
        "think",
        "try",
        "understand",
        "use",
        "wait",
        "walk",
        "want",
        "work",
        "write",
    ];

    const verbs2 = [
        "run",
        "walk",
        "jump",
        "swim",
        "read",
        "write",
        "speak",
        "listen",
        "cook",
        "build",
        "drive",
        "learn",
        "teach",
        "work",
        "play",
        "draw",
        "sing",
        "dance",
        "sit",
        "stand",
        "watch",
        "help",
        "grow",
        "find",
        "show",
        "buy",
        "sell",
        "give",
        "take",
        "open",
        "close",
        "laugh",
        "cry",
        "travel",
        "explore",
        "understand",
        "improve",
        "discover",
        "support",
        "hope",
        "study",
        "solve",
        "manage",
        "lead",
        "organize",
        "measure",
        "adjust",
        "compare",
        "decide",
        "perform",
        "train",
        "design",
        "develop",
        "fix",
        "connect",
        "consider",
        "choose",
        "follow",
        "guide",
        "answer",
        "explain",
        "invite",
        "allow",
        "cancel",
        "plan",
        "prepare",
        "arrange",
        "discuss",
        "share",
        "remember",
        "forget",
        "meet",
        "join",
        "enter",
        "exit",
        "send",
        "receive",
        "start",
        "finish",
        "order",
        "record",
        "paint",
        "calculate",
        "calculate",
        "save",
        "protect",
        "create",
        "achieve",
        "communicate",
        "participate",
        "collaborate",
        "motivate",
        "dedicate",
        "review",
        "test",
        "analyze",
        "select",
        "invest",
        "generate",
        "define",
        "launch",
        "prevent",
        "control",
        "focus",
        "maintain",
        "describe",
        "examine",
        "demonstrate",
        "invent",
        "examine",
        "confirm",
        "suggest",
        "recommend",
        "operate",
        "imagine",
        "predict",
        "upgrade",
        "handle",
        "face",
        "repair",
        "collect",
        "advise",
        "negotiate",
        "estimate",
        "locate",
        "contain",
        "distribute",
        "earn",
        "fix",
        "print",
        "modify",
        "analyze",
        "deliver",
        "organize",
        "sort",
        "collaborate",
        "extend",
        "strengthen",
        "focus",
        "support",
        "represent",
        "inspire",
        "educate",
        "simulate",
        "provide",
        "demonstrate",
        "expand",
        "encourage",
        "interpret",
        "emphasize",
        "illustrate",
        "supply",
        "survey",
        "forecast",
        "exhibit",
        "integrate",
        "specialize",
        "broadcast",
        "negotiate",
        "describe",
        "outline",
        "initiate",
        "enforce",
        "pursue",
        "negotiate",
        "encounter",
        "interpret",
        "validate",
        "document",
        "illustrate",
        "measure",
        "notify",
        "observe",
        "project",
        "estimate",
        "compose",
        "secure",
        "attend",
        "supply",
        "survey",
        "program",
        "train",
        "calculate",
        "contribute",
        "operate",
        "monitor",
        "initiate",
        "test",
        "upgrade",
        "correct",
        "instruct",
        "install",
        "generate",
        "test",
        "predict",
        "clarify",
        "diagnose",
        "compile",
        "diagnose",
        "convert",
        "support",
        "upgrade",
        "complete",
        "perform",
        "handle",
        "submit",
        "ensure",
        "confirm",
        "arrange",
        "guide",
        "document",
        "update",
        "ensure",
        "recommend",
        "train",
        "install",
        "guide",
        "invest",
        "submit",
        "purchase",
        "operate",
        "perform",
        "validate",
        "rebuild",
        "locate",
        "approve",
        "demonstrate",
        "refine",
        "forecast",
        "calculate",
        "construct",
        "present",
        "analyze",
        "compute",
        "repair",
        "arrange",
        "clarify",
        "confirm",
        "contribute",
        "notify",
        "submit",
        "examine",
        "debug",
        "allocate",
        "engineer",
        "analyze",
        "collect",
        "troubleshoot",
        "debug",
        "organize",
        "simulate",
        "design",
        "streamline",
        "revise",
        "verify",
        "confirm",
        "transform",
        "review",
        "reorganize",
        "research",
        "launch",
        "distribute",
        "facilitate",
        "enhance",
        "balance",
        "assemble",
        "monitor",
        "engineer",
        "optimize",
        "inspire",
        "motivate",
        "correct",
        "repair",
        "revise",
        "negotiate",
        "invest",
        "compile",
        "develop",
        "formulate",
        "define",
        "support",
        "implement",
        "deploy",
        "initiate",
        "design",
        "integrate",
        "collaborate",
        "facilitate",
        "manage",
        "direct",
        "install",
        "adjust",
        "estimate",
        "advocate",
        "engage",
        "explore",
        "connect",
        "resolve",
        "conclude",
        "identify",
        "generate",
        "encourage",
        "inspect",
        "assist",
        "correct",
        "influence",
        "coordinate",
        "restructure",
        "maintain",
        "sustain",
        "ensure",
        "recommend",
        "evaluate",
        "support",
        "anticipate",
        "distribute",
        "solve",
        "improve",
        "collaborate",
        "handle",
        "suggest",
        "implement",
        "allocate",
        "compile",
        "present",
        "adapt",
        "assemble",
        "update",
        "record",
        "predict",
        "purchase",
        "construct",
        "install",
        "validate",
        "modify",
        "redesign",
        "prepare",
        "organize",
        "operate",
        "conduct",
        "assist",
        "manage",
        "coordinate",
        "repair",
        "upgrade",
        "validate",
        "debug",
        "monitor",
        "analyze",
        "install",
        "predict",
        "assess",
        "calculate",
        "perform",
        "assist",
        "calculate",
        "coordinate",
        "streamline",
        "recommend",
        "launch",
        "guide",
        "rebuild",
        "troubleshoot",
        "monitor",
        "debug",
        "install",
        "inspect",
        "formulate",
        "organize",
        "transform",
        "facilitate",
        "develop",
    ];

    const connectors = [
        "in addition",
        "however",
        "furthermore",
        "on the other hand",
        "nevertheless",
        "as well as",
        "either",
        "nor",
        "yet",
        "since",
        "until",
        "once",
        "unless",
        "due to",
        "in case",
        "on condition that",
        "in order to",
        "whether",
        "even if",
        "as soon as",
        "provided that",
        "before",
        "after",
        "whereas",
        "by the time",
        "while",
        "when",
        "whenever",
        "now that",
        "even so",
        "consequently",
        "as a result",
        "in spite of",
        "likewise",
        "similarly",
        "otherwise",
        "instead",
        "wherever",
        "because of",
        "in contrast",
        "besides",
        "meanwhile",
        "thus",
        "hence",
        "accordingly",
        "apart from",
        "not only",
        "for instance",
        "for example",
        "such as",
        "like",
        "in comparison",
        "so as to",
        "in the event that",
        "similarly",
        "therefore",
        "so long as",
        "insofar as",
        "just as",
        "nonetheless",
        "if only",
        "inasmuch as",
        "rather than",
        "at the same time",
        "otherwise",
        "except",
        "along with",
        "beside",
        "next to",
        "despite the fact that",
        "provided",
        "in the same way",
        "notwithstanding",
        "so much so that",
        "in the meantime",
        "whilst",
        "due to the fact that",
        "inasmuch as",
        "thereby",
        "henceforth",
        "regardless of",
        "such that",
        "for this reason",
        "for the purpose of",
        "assuming that",
        "as though",
        "given that",
        "seeing that",
        "in light of",
        "owing to",
        "whereupon",
        "provided that",
        "as if",
        "lest",
        "although",
        "rather",
        "wherein",
        "in particular",
        "on the condition that",
        "as far as",
        "by reason of",
        "on behalf of",
        "given the fact that",
        "over and above",
        "without regard to",
        "up until",
        "in keeping with",
        "in place of",
        "in preference to",
        "forasmuch as",
        "until such time as",
        "in line with",
        "in opposition to",
        "inasmuch",
        "in accordance with",
        "as per",
        "in conjunction with",
        "in the wake of",
        "by virtue of",
        "under the circumstances",
        "with regard to",
        "with a view to",
        "contrary to",
        "irrespective of",
        "insofar as",
        "consistent with",
        "in contrast to",
        "dependent on",
        "insofar as",
        "in recognition of",
        "in response to",
        "by comparison",
        "to that effect",
        "in turn",
        "despite the fact",
        "with respect to",
        "having said that",
        "all the same",
        "be that as it may",
        "in addition to",
        "on the grounds that",
        "under no circumstances",
        "under normal circumstances",
        "to put it another way",
        "by contrast",
        "on top of that",
        "for the time being",
        "in view of",
        "needless to say",
        "sooner or later",
        "for want of",
        "in proportion to",
        "bearing in mind",
        "in lieu of",
        "prior to",
        "beyond that",
        "in spite of the fact",
        "as opposed to",
        "even after",
        "once again",
        "as soon as",
        "in case of",
        "without a doubt",
        "at which point",
        "until now",
        "upon",
        "without exception",
        "on account of",
        "in advance of",
        "in conjunction",
        "on the understanding that",
        "in respect of",
        "in exchange for",
        "in accordance",
        "even though",
        "given the circumstances",
        "despite the fact",
        "in regard to",
        "in consideration of",
        "for all intents and purposes",
        "irrespective",
        "on that note",
        "provided it",
        "beyond",
        "under those conditions",
        "accordingly",
        "so to speak",
        "if and only if",
        "as a consequence of",
        "conversely",
        "by reason",
        "to the extent",
        "over and above",
        "without delay",
        "on the understanding",
        "when compared to",
        "to say nothing of",
        "as concerns",
        "even though",
        "on second thought",
        "apart from that",
        "regardless of the fact",
        "by that time",
        "in connection with",
        "similarly",
        "if so",
        "having regard to",
        "seeing as",
        "not to mention",
        "at length",
        "in addition",
        "at any rate",
        "on occasion",
        "on balance",
        "insofar",
        "as a result of",
        "if applicable",
        "insofar as possible",
        "subject to",
        "in keeping with",
        "on this occasion",
        "as it were",
        "if nothing else",
        "in no way",
        "in the case of",
        "on that basis",
        "in the face of",
        "owing to the fact",
        "in connection",
        "to this effect",
        "if applicable",
        "as per usual",
        "in this context",
        "with reference to",
        "consistent with",
        "on the basis of",
        "under these circumstances",
        "under pressure",
        "without question",
        "so to speak",
        "for all intents",
        "for this reason",
        "in that sense",
        "in light",
        "until further notice",
        "in short",
        "in opposition",
        "with this in mind",
        "at the same time",
        "beyond belief",
        "to the point",
        "in consideration",
        "notwithstanding",
        "in due course",
        "in line",
        "in conformity",
        "in response",
        "by way of",
        "under no illusion",
        "by contrast",
        "subject to change",
        "on good terms",
        "under normal",
        "under no obligation",
        "under such circumstances",
        "with the exception",
        "for example",
        "under certain",
        "in turn",
        "in so far",
        "in other words",
        "not to mention",
        "with that being said",
        "in reality",
        "in general terms",
        "under no circumstances",
        "under such conditions",
        "over time",
        "given these",
        "from time to time",
        "up to this point",
        "in no uncertain terms",
        "in some respects",
        "in most cases",
        "all in all",
        "on second thoughts",
        "on a side note",
        "in closing",
        "to sum up",
        "if necessary",
        "as appropriate",
        "for good measure",
        "as necessary",
        "when appropriate",
        "given that",
        "on occasion",
        "under normal conditions",
        "on rare occasions",
        "subject to approval",
        "without further ado",
        "in respect",
        "to put it simply",
        "subject to availability",
        "when in doubt",
        "in general",
        "as far as",
        "as long as",
        "on second thought",
        "to a large extent",
        "under certain circumstances",
        "with regard",
        "in conclusion",
        "in spite of the fact that",
        "in no way",
        "as far as",
        "without any further",
        "without a shadow of a doubt",
        "with no exception",
        "on a different note",
        "in due course",
        "under the influence of",
        "in any event",
        "under the terms of",
        "with immediate effect",
        "in no way",
        "in full accordance",
        "in relation to",
        "with due regard",
        "to put it bluntly",
        "by comparison",
        "for clarity's sake",
        "to a certain extent",
        "with respect",
        "without further",
        "in that regard",
        "in this light",
        "in summary",
        "with regard to",
        "in some cases",
        "in view",
        "without prejudice",
        "in full force",
        "under no obligation",
        "with the exception",
        "to an extent",
        "in large part",
        "with no reservation",
        "in compliance with",
        "in general terms",
        "in final analysis",
    ];

    // Hàm tạo câu ngẫu nhiên
    function createRandomSentence() {
        const word1 = words[Math.floor(Math.random() * words.length)];
        const verb1 = verbs[Math.floor(Math.random() * verbs.length)];
        const word2 = words[Math.floor(Math.random() * words.length)];
        const connector1 =
            connectors[Math.floor(Math.random() * connectors.length)];
        const word3 = words[Math.floor(Math.random() * words.length)];
        const verb2 = verbs[Math.floor(Math.random() * verbs.length)];
        const word4 = words[Math.floor(Math.random() * words.length)];
        // const connector2 =
        //     connectors[Math.floor(Math.random() * connectors.length)];
        // const word5 = words[Math.floor(Math.random() * words.length)];
        // const verb3 = verbs[Math.floor(Math.random() * verbs.length)];
        // const word6 = words[Math.floor(Math.random() * words.length)];

        // return `${word1} ${verb1} ${word2}, ${connector1} ${word3} ${verb2} ${word4} ${connector2} ${word5} ${verb3} ${word6}.`;

        return `${word1} ${verb1} ${word2}, ${connector1} ${word3} ${verb2} ${word4}.`;
    }

    // Hàm tạo đoạn văn bằng cách kết hợp nhiều câu ngẫu nhiên
    function generateRandomText() {
        let combinedText = "";
        const numberOfSentences = 70; // Số lượng câu muốn tạo

        for (let i = 0; i < numberOfSentences; i++) {
            combinedText += createRandomSentence() + " ";
        }

        // Hiển thị đoạn văn kết hợp
        document.getElementById("randomText").innerText = combinedText.trim();
    }
    generateRandomText();
    document
        .getElementById("randomButton")
        .addEventListener("click", generateRandomText);

    function copyToClipboard(text) {
        const textArea = document.createElement("textarea");
        textArea.value = text;
        document.body.appendChild(textArea);
        textArea.select();
        document.execCommand("copy");
        document.body.removeChild(textArea);

        // Hiển thị thông báo đã sao chép
        document.querySelector(".copied").style.display = "inline";
        setTimeout(() => {
            document.querySelector(".copied").style.display = "none";
        }, 1000);
    }

    document
        .getElementById("copyTextButton")
        .addEventListener("click", function () {
            const textToCopy = document.getElementById("randomText").innerText;
            copyToClipboard(textToCopy);
        });
    // document
    //     .getElementById("randomButton")
    //     .addEventListener("click", function () {
    //         const textToCopy = document.getElementById("randomText").innerText;
    //         copyToClipboard(textToCopy);
    //     });
    document
        .getElementById("copyButton")
        .addEventListener("click", function () {
            const shareLink = document.getElementById("shareLink");
            shareLink.select();
            document.execCommand("copy");
            document.querySelector(".copied").style.display = "inline";
            setTimeout(() => {
                document.querySelector(".copied").style.display = "none";
            }, 1000);
        });
    document.getElementById("shareLink").addEventListener("click", function () {
        const shareLink = document.getElementById("shareLink");
        shareLink.select();
        document.execCommand("copy");
        document.querySelector(".copied").style.display = "inline";
        setTimeout(() => {
            document.querySelector(".copied").style.display = "none";
        }, 1000);
    });
};
